FROM ubuntu:latest
RUN apt-get -y update --fix-missing
RUN apt-get -y upgrade
RUN apt-get install git -y
RUN apt-get install nodejs -y
RUN apt-get install npm -y
COPY . node-chat-app/
WORKDIR node-chat-app